/run/initialize
/control/verbose 2
/run/verbose 2
/tracking/verbose 0
/Sim/eventVerbose 0

/Sim/detector/defaults
/Sim/oneStepPrimaries false

/Sim/detector/volumes/wls 1
/Sim/detector/volumes/sim 0
/Sim/detector/nfibers 15
/Sim/detector/WLSScintYield 10000
/gun/particle e-
/gun/energy 511 keV

/analysis/h1/set 3 100 -1 10000 
/analysis/h1/set 4 100 -1 100
/analysis/h1/set 5 100 -1 10000

/run/printProgress 10
/run/beamOn 1000
